// Tasks
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';
export const CREATE_NEW_TASK_ADMIN = 'CREATE_NEW_TASK_ADMIN';
export const EMPLOYEE_COMPLETED_TASKS = 'EMPLOYEE_COMPLETED_TASKS';
export const EMPLOYEE_TASK_LIST = 'EMPLOYEE_TASK_LIST';
export const COMPANY_TASK_LIST = 'COMPANY_TASK_LIST';
export const FETCH_COMPANY_TASKS_SUCCESS = 'FETCH_COMPANY_TASKS_SUCCESS';
export const EMPLOYEE_TASK_PROCESS = 'EMPLOYEE_TASK_PROCESS';
export const COMPANY_TASK_DETAILS = 'COMPANY_TASK_DETAILS';
export const COMPANY_TASK_DETAILS_SUCCESS = 'COMPANY_TASK_DETAILS_SUCCESS';
export const EMPLOYEE_TASK_COMPLETE = 'EMPLOYEE_TASK_COMPLETE';
export const COMPANY_TASK_DELETE = 'COMPANY_TASK_DELETE';
export const COMPANY_TASK_DELETE_SUCCESS = 'COMPANY_TASK_DELETE_SUCCESS';

// auth
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

//profile
export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const UPDATE_COMAPNY_PROFILE = 'UPDATE_COMAPNY_PROFILE';
export const GET_COMPANY_PROFILE_SUCCESS = 'GET_COMPANY_PROFILE_SUCCESS';
export const UPDATE_PROFILE_EMPLOYEE = 'UPDATE_PROFILE_EMPLOYEE';
export const UPDATE_PROFILE_EMPLOYEE_SUCCESS =
  'UPDATE_PROFILE_EMPLOYEE_SUCCESS';

//employee
export const GET_COMPANY_EMPLOYEES = 'GET_COMPANY_EMPLOYEES';
export const INVITE_EMPLOYEE_TO_COMPANY = 'INVITE_EMPLOYEE_TO_COMPANY';
export const GET_COMPANY_EMPLOYEES_SUCCESS = 'GET_COMPANY_EMPLOYEES_SUCCESS';
export const DELETE_COMPANY_EMPLOYEE = 'DELETE_COMPANY_EMPLOYEE';
export const DELETE_COMPANY_EMPLOYEES_SUCCESS =
  'DELETE_COMPANY_EMPLOYEES_SUCCESS';
